# Generated by Django 4.2.7 on 2024-02-28 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TRYST', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('phone', models.PositiveBigIntegerField()),
                ('dob', models.DateField()),
                ('collegeName', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('StdPhoto', models.ImageField(upload_to='images', width_field='width')),
                ('StdAadhar', models.ImageField(upload_to='images', width_field='width')),
            ],
        ),
    ]
