# Generated by Django 4.2.7 on 2024-03-03 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TRYST', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('phone', models.PositiveBigIntegerField()),
                ('collegeName', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('StdIDCard', models.ImageField(upload_to='images')),
                ('UID', models.IntegerField(default=0)),
                ('otp', models.IntegerField(default=0)),
                ('entryTime', models.IntegerField(default=0)),
                ('Std_qr_code', models.ImageField(blank=True, upload_to='code')),
            ],
        ),
    ]
