# Generated by Django 4.2.7 on 2024-03-04 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TRYST', '0002_registrationform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrationform',
            name='UID',
            field=models.CharField(max_length=7),
        ),
    ]
