# Generated by Django 4.2.7 on 2024-02-28 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TRYST', '0002_registrationform'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationform',
            name='UID',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='registrationform',
            name='enteryTime',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='registrationform',
            name='otp',
            field=models.IntegerField(default=0),
        ),
    ]
