# Generated by Django 4.2.7 on 2024-03-17 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TRYST', '0003_alter_registrationform_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationform',
            name='course',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='registrationform',
            name='year',
            field=models.IntegerField(default=0),
        ),
    ]
