# Generated by Django 4.2.7 on 2024-02-29 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TRYST', '0003_registrationform_uid_registrationform_enterytime_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registrationform',
            old_name='enteryTime',
            new_name='entryTime',
        ),
        migrations.RemoveField(
            model_name='registrationform',
            name='StdAadhar',
        ),
        migrations.RemoveField(
            model_name='registrationform',
            name='StdPhoto',
        ),
        migrations.RemoveField(
            model_name='registrationform',
            name='dob',
        ),
        migrations.AddField(
            model_name='registrationform',
            name='StdIDCard',
            field=models.ImageField(default=0, upload_to='images'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registrationform',
            name='Std_qr_code',
            field=models.ImageField(blank=True, upload_to='code'),
        ),
    ]
