# Generated by Django 4.2.7 on 2024-02-28 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TRYST', '0003_registrationform_uid_registrationform_enterytime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrationform',
            name='StdAadhar',
            field=models.ImageField(upload_to='images'),
        ),
        migrations.AlterField(
            model_name='registrationform',
            name='StdPhoto',
            field=models.ImageField(upload_to='images'),
        ),
    ]
