# Generated by Django 4.2.7 on 2024-02-29 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TRYST', '0004_alter_registrationform_stdaadhar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationform',
            name='Std_qr_code',
            field=models.ImageField(blank=True, upload_to='code'),
        ),
    ]
