# Generated by Django 4.2.7 on 2024-02-29 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TRYST', '0004_rename_enterytime_registrationform_entrytime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrationform',
            name='Std_qr_code',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
    ]
