# Generated by Django 4.2.7 on 2024-02-29 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TRYST', '0005_registrationform_std_qr_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registrationform',
            old_name='StdPhoto',
            new_name='StdIDCard',
        ),
        migrations.RemoveField(
            model_name='registrationform',
            name='StdAadhar',
        ),
        migrations.RemoveField(
            model_name='registrationform',
            name='dob',
        ),
    ]
