# Generated by Django 4.2.7 on 2024-02-29 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TRYST', '0006_rename_stdphoto_registrationform_stdidcard_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registrationform',
            old_name='enteryTime',
            new_name='entryTime',
        ),
    ]
